// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadImage.Models
{
    public partial class Img
    {
        public int ImgId { get; set; }
        public string Imgname { get; set; }
        public byte[] ImgType { get; set; }
    }
}